#集合kafka
cittt:
  kafka:
    binder:
      brokers: 192.168.200.134:9092
      zk-nodes: 192.168.200.134:2181
    group: cittt-group

spring:
  thymeleaf:
    prefix: classpath:/templates/

echartsConfig:
  arrayProps: 1,2,3,4,5